require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  DisplayCopNames: true
  EnabledByDefault: true
  TargetRubyVersion: 2.7.1
  Exclude:
    - 'bin/*'
    - 'config/**/*'
    - 'db/*'

Rails:
  Enabled: true

Metrics/MethodLength:
  Max: 50

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Style/Copyright:
  Enabled: false

Lint/ConstantResolution:
  Enabled: false

Style/DocumentationMethod:
  Enabled: false

Lint/NumberConversion:
  Enabled: false


